version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: smart_restaurant_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: smart_restaurant

volumes:
  mongo_data:
